#ifndef _ENUMS_H
#define _ENUMS_H

enum CHARACTER_CLASS { MAGE, ROGUE, WARRIOR, CHARACTER_CLASS_COUNT };

enum ARMOR_CLASS { LIGHT, MEDIUM, HEAVY, ARMOR_CLASS_COUNT };

enum PLAYER_DIRECTION {
  PLAYER_SOUTH,
  PLAYER_SOUTH_WEST_1,
  PLAYER_SOUTH_WEST_2,
  PLAYER_SOUTH_WEST_3,
  PLAYER_WEST,
  PLAYER_NORTH_WEST_1,
  PLAYER_NORTH_WEST_2,
  PLAYER_NORTH_WEST_3,
  PLAYER_NORTH,
  PLAYER_NORTH_EAST_1,
  PLAYER_NORTH_EAST_2,
  PLAYER_NORTH_EAST_3,
  PLAYER_EAST,
  PLAYER_SOUTH_EAST_1,
  PLAYER_SOUTH_EAST_2,
  PLAYER_SOUTH_EAST_3,
  PLAYER_DIRECTION_COUNT
};

enum MONSTER_DIRECTION {
  MONSTER_SOUTH_WEST,
  MONSTER_WEST,
  MONSTER_NORTH_WEST,
  MONSTER_NORTH,
  MONSTER_NORTH_EAST,
  MONSTER_EAST,
  MONSTER_SOUTH_EAST,
  MONSTER_SOUTH,
  MONSTER_DIRECTION_COUNT
};

enum MAIN_MENU_SELECTIONS {
  START_GAME,
  SHOW_INTRO,
  CREDITS,
  QUIT,
  MAIN_MENU_ITEM_COUNT
};

enum GAME_START_MODE { NEW_GAME, LOAD_GAME };

enum PATH_CODE {
  PATH_NONE,
  UP,
  LEFT,
  RIGHT,
  DOWN,
  UP_LEFT,
  UP_RIGHT,
  DOWN_RIGHT,
  DOWN_LEFT,
  PATH_CODE_COUNT
};

enum PLAYER_STATE {
  PLAYER_NO_STATE,
  PLAYER_STANDING,
  PLAYER_MOVING,
  PLAYER_ATTACKING,
  PLAYER_STATE_COUNT
};

enum PLAYER_DESTINATION_ACTION {
  PLAYER_DESTINATION_NONE,
  PLAYER_DESTINATION_STAND,
  PLAYER_DESTINATION_ATTACK,
  PLAYER_DESTINATION_PICK_ITEM,
  PLAYER_DESTINATION_TALK,
  PLAYER_DESTINATION_INTERACT_OBJECT,
  PLAYER_DESTINATION_ACTION_COUNT
};

enum MONSTER_STATE {
  MONSTER_STANDING,
  MONSTER_MOVING,
  MONSTER_ATTACKING,
  MONSTER_DEAD,
  MONSTER_NO_STATE,
  MONSTER_STATE_COUNT
};

enum SPRITE {
  // chars
  SPRITE_WARRIOR_IDLE,
  SPRITE_WARRIOR_WALK,
  SPRITE_WARRIOR_ATTACK,
  SPRITE_SKELETON_IDLE,
  SPRITE_SKELETON_WALK,
  SPRITE_SKELETON_ATTACK,
  SPRITE_SKELETON_DEAD,

  // land tiles
  SPRITE_GROVEL,
  SPRITE_STONE,

  // wall tiles
  WALL_1_EAST,
  WALL_1_NORTH,

  // ground animations
  EARTH_CRACK,

  // misc
  SPRITE_CURSOR,
  SPRITE_SELECTION,
  ORB_EMPTY,
  ORB_HEALTH,
  ORB_MANA,

  MAX_SPRITES
};

enum ANIMATION {
  ANIM_NONE,
  ANIM_WARRIOR_IDLE,
  ANIM_WARRIOR_WALK,
  ANIM_WARRIOR_ATTACK,
  ANIM_SKELETON_IDLE,
  ANIM_SKELETON_WALK,
  ANIM_SKELETON_ATTACK,
  ANIM_SKELETON_DEAD,
  ANIM_EARTH_CRACK,
  MAX_ANIMATIONS
};

enum DAMAGE_TYPE {
  DAMAGE_NONE,
  DAMAGE_PHYSICAL,
  DAMAGE_FIRE,
  DAMAGE_FROST,
  DAMAGE_LIGHTNING,
  DAMAGE_ARCANE,
  DAMAGE_NATURE,
  DAMAGE_TYPE_COUNT
};

enum PROJECTILE_PATH {
  PROJECTILE_PATH_NONE,
  PROJECTILE_PATH_STRAIGHT,
  PROJECTILE_PATH_COUNT
};

enum SPELL_TYPE {
  SPELL_TYPE_NONE,
  SPELL_TYPE_TARGET_ONE,
  SPELL_TYPE_TARGET_AREA,
  SPELL_TYPE_TARGET_PLAYER_POSITION,
  SPELL_TYPE_FIRE_PROJECTILE,
  SPELL_TYPE_TARGET_SELF,
  SPELL_TYPE_SUMMON,
  SPELL_TYPE_COUNT
};

enum SPELL_ID {
  SPELL_BASE_ATTACK,
  SPELL_BASH,
  SPELL_STOMP,
  SPELL_QUAKE,
  SPELL_FIREBALL,
  SPELL_COUNT
};

#endif
