#include "spell.h"

Spell gSpells[SPELL_COUNT] = {{SPELL_BASE_ATTACK, "Attack",
                               SPELL_TYPE_TARGET_ONE, DAMAGE_PHYSICAL, 0, 1.0,
                               2.0, 0.0, false},
                              {SPELL_BASH, "Bash", SPELL_TYPE_TARGET_ONE,
                               DAMAGE_PHYSICAL, 4, 1.5, 2.0, 0.0, false},
                              {SPELL_STOMP,
                               "Stomp",
                               SPELL_TYPE_TARGET_PLAYER_POSITION,
                               DAMAGE_PHYSICAL,
                               8,
                               0.8,
                               0.0,
                               2.0,
                               true,
                               {ANIM_EARTH_CRACK, 100}},
                              {SPELL_QUAKE,
                               "Quake",
                               SPELL_TYPE_TARGET_AREA,
                               DAMAGE_PHYSICAL,
                               16,
                               2.0,
                               8.0,
                               3.0,
                               true,
                               {ANIM_EARTH_CRACK, 100}},
                              {SPELL_FIREBALL,
                               "Fireball",
                               SPELL_TYPE_FIRE_PROJECTILE,
                               DAMAGE_FIRE,
                               10,
                               2,
                               5.0,
                               2.0,
                               false,
                               {ANIM_NONE},
                               {ANIM_NONE, PROJECTILE_PATH_STRAIGHT, 1.0}}};
